name: 'Check for Changes'
description: 'Checks for changes in the requested path.'

inputs:
  path:
    description: 'The path to check for files in.'
    required: true

outputs:
  found-changes:
    description: 'Whether or not changes were found.'
    value: ${{ steps.check-changes.outputs.found-changes }}

runs:
  using: 'composite'
  steps:
    - id: check-changes
      shell: bash
      run: |
        git fetch
        CHANGES=$(git diff --name-only HEAD origin/${{ github.base_ref }})
        if [[ -z "$(grep -E "^sec/|^${{ inputs.path }}/" <<< "$CHANGES")" ]]; then
          echo "No changes were found in ${{ inputs.path }}."
          echo "found-changes=1" >> $GITHUB_OUTPUT
        else
          echo "Found changed in ${{ inputs.path }}."
          echo "found-changes=0" >> $GITHUB_OUTPUT
        fi
