name: TS Plugin Workers Version Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Version
        uses: .github/actions/version-check
