name: TS Plugin Workers Wasm Package Version Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  wasm-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check version
        uses: ./.github/actions/check-version
        with:
          project_path: packages/wasm
