name: TS Plugin Workers Package Version Check

on:
  pull_request:
    paths:
      - 'packages/plugin/src/**'
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  plugin-version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check version
        uses: ./.github/actions/check-version
        with:
          project_path: packages/plugin
