name: TS Plugin Workers Version Check

on:
  pull_request:
    paths:
      - 'src/**'
    branches: [main]
    types: [opened, synchronize, labeled, unlabeled]
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Check for "skip-version-bump" label
      #   id: check_label
      #   shell: bash
      #   run: |
      #     LABEL=$(echo "${{ join(github.event.pull_request.labels.*.name) }}" | grep -o "skip-version-bump" || true)
      #     if [[ "$LABEL" == "skip-version-bump" ]]; then
      #       echo "Skip version bump label found. Exiting."
      #       echo "::set-output name=SKIP::yes"
      #     else
      #       echo "::set-output name=SKIP::no"
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Get base branch version
      #   if: steps.check_label.outputs.SKIP != "yes"
      #   shell: bash
      #   run: |
      #     git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
      #     echo "BASE_VERSION=$(git show origin/${{ github.base_ref }}:package.json | node -p "require('./package.json').version")" >> $GITHUB_ENV
      #     echo "Base version was $BASE_VERSION"

      # - name: Get PR branch version
      #   if: steps.check_label.outputs.SKIP != "yes"
      #   shell: bash
      #   run: |
      #     echo "PR_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      #     echo "Base version was $BASE_VERSION"
      #     echo "PR version was $BASE_VERSION"

      # - name: Check if version is incremented
      #   if: steps.check_label.outputs.SKIP != "yes"
      #   shell: bash
      #   run: |
      #     function version { echo "$@" | awk -F. "{ printf("%d%03d%03d", $1,$2,$3); }"; }
      #     if [ $(version $PR_VERSION) -le $(version $BASE_VERSION) ]; then
      #       echo "Error: The version in package.json has not been incremented."
      #       exit 1
      #     else
      #       echo "Version incremented in package.json. Exiting."
      #       exit 0

      # - name: Add comment if version is not incremented
      #   if: ${{ failure() }}
      #   shell: bash
      #   run: |
      #     MESSAGE="Error: The version in package.json has not been incremented."
      #     echo $MESSAGE
      #     echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Post comment
      #   if: ${{ failure() }}
      #   uses: actions/github-script@v5
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       const message = process.env.MESSAGE;
      #       github.rest.issues.createComment({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         issue_number: context.issue.number,
      #         body: message
      #       });
