name: CI

on:
  pull_request:
    branches: ['**']

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies with Bun
        run: bun install
      - name: Build project
        run: bun run build
      - name: Lint with ESLint
        run: bun run lint
      - name: Check formatting with Prettier
        run: bun run format-check
