name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Install node packages
        run: pnpm install

      - name: Run linting checks
        run: pnpm turbo lint

      - name: Check formatting
        run: |
          pnpm run format:check
          pnpm turbo format:check

      - name: Set up wasm-pack
        uses: ./.github/actions/wasm-pack/setup

      - name: Build all projects
        run: pnpm turbo build
