name: Publish @timsexperiments/ts-plugin-workers Packages

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  publish-wasm:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check @timsexperiments/ts-plugin-workers-wasm version
        id: check-version
        if: github.event_name != 'workflow_dispatch'
        uses: ./.github/actions/check-version
        with:
          project_path: packages/wasm

      - name: Set up wasm-pack
        if: steps.check-version.outputs.bumped == 0 || GitHub.event_name == 'workflow_dispatch'
        uses: ./.github/actions/wasm-pack/setup

      - name: Publish @timsexperiments/ts-plugin-workers-wasm
        if: steps.check-version.outputs.bumped == 0 || github.event_name == 'workflow_dispatch'
        uses: ./.github/actions/publish
        with:
          project_path: packages/wasm
          npm_token: ${{ secrets.NPM_TOKEN }}

  publish-plugin:
    if: github.event.pull_request.merged == true
    needs:
      - publish-wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check @timsexperiments/ts-plugin-workers version
        id: check-version
        if: github.event_name != 'workflow_dispatch'
        uses: ./.github/actions/check-version
        with:
          project_path: packages/plugin

      - name: Publish @timsexperiments/ts-plugin-workers
        if: steps.check-version.outputs.bumped == 0 || GitHub.event_name == 'workflow_dispatch'
        uses: ./.github/actions/publish
        with:
          project_path: packages/plugin
          npm_token: ${{ secrets.NPM_TOKEN }}
